services:
  jenkins:
    image: jenkins/jenkins:2.452.2-jdk17
    restart: always
    user: "root"
    #working_dir: /home/node/app
    privileged: true
    volumes:
      - ./jenkins_sandbox_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Data_1:/Data_1:rw
    ports:
      - 8080:8080
      - 50000:50000
    build:
      context: ./
      dockerfile: Dockerfile